# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('limit', models.IntegerField()),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('sport', models.CharField(choices=[('f', 'football'), ('b', 'baseball'), ('k', 'basketball')], max_length=1)),
                ('pts_last', models.IntegerField()),
                ('pts_proj', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.League')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='squad',
            name='baseball1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseball1', to='app.Team'),
        ),
        migrations.AddField(
            model_name='squad',
            name='baseball2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseball2', to='app.Team'),
        ),
        migrations.AddField(
            model_name='squad',
            name='basketball1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball1', to='app.Team'),
        ),
        migrations.AddField(
            model_name='squad',
            name='basketball2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball2', to='app.Team'),
        ),
        migrations.AddField(
            model_name='squad',
            name='football1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football1', to='app.Team'),
        ),
        migrations.AddField(
            model_name='squad',
            name='football2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football2', to='app.Team'),
        ),
        migrations.AddField(
            model_name='squad',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.League'),
        ),
        migrations.AddField(
            model_name='squad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
