# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_league_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.League')),
            ],
        ),
    ]
